### ISSUE TITLE
diff-viewer is broken

### ISSUE THREAD

**Issue by FabriceSalvaire** [FabriceSalvaire/CodeReview#23]
Traceback (most recent call last):
File "/home/opt/python-virtual-env/py36/bin/diff-viewer", line 4, in (module)
__import__('pkg_resources').run_script('CodeReview==0.3.3', 'diff-viewer')
File "/home/opt/python-virtual-env/py36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 748, in run_script
self.require(requires)[0].run_script(script_name, ns)
File "/home/opt/python-virtual-env/py36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1517, in run_script
exec(code, namespace, namespace)
File "/home/opt/python-virtual-env/py36/lib/python3.6/site-packages/CodeReview-0.3.3-py3.6-linux-x86_64.egg/EGG-INFO/scripts/diff-viewer", line 70, in (module)
application = DiffViewerApplication(args)
File "/home/opt/python-virtual-env/py36/lib/python3.6/site-packages/CodeReview-0.3.3-py3.6-linux-x86_64.egg/CodeReview/GUI/DiffViewer/DiffViewerApplication.py", line 46, in __init__
self._main_window = DiffViewerMainWindow()
File "/home/opt/python-virtual-env/py36/lib/python3.6/site-packages/CodeReview-0.3.3-py3.6-linux-x86_64.egg/CodeReview/GUI/DiffViewer/DiffViewerMainWindow.py", line 67, in __init__
self._create_toolbar()
File "/home/opt/python-virtual-env/py36/lib/python3.6/site-packages/CodeReview-0.3.3-py3.6-linux-x86_64.egg/CodeReview/GUI/DiffViewer/DiffViewerMainWindow.py", line 214, in _create_toolbar
self._stage_action,
AttributeError: 'DiffViewerMainWindow' object has no attribute '_stage_action'

**Comment by FabriceSalvaire** [comment]
fixed in 0a0d91
