### ISSUE TITLE
I can't run it after install successfully

### ISSUE THREAD

**Issue by tim3385** [FabriceSalvaire/CodeReview#45]
I have installed CodeReview(pip install CodeReview) with the dependencies. 
```
Installing collected packages: PyQt5-sip, PyQt5, Pygments, pycparser, six, cffi, pygit2, PyYAML, CodeReview
Successfully installed CodeReview-1.0.0 PyQt5-5.12 PyQt5-sip-4.19.14 PyYAML-3.13 Pygments-2.3.1 cffi-1.12.1 pycparser-2.17 pygit2-0.27.4 six-1.12.0
```

But I can't run it.
```
$ pyqgit
Traceback (most recent call last):
  File "/usr/local/bin/pyqgit", line 4, in <module>
    __import__('pkg_resources').run_script('CodeReview==1.0.0', 'pyqgit')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1429, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/pyqgit' not found in metadata at '/home/tim/.local/lib/python3.6/site-packages/CodeReview-1.0.0.dist-info'
```

And I have set the LD_LIBRARY_PATH
```
$ echo $LD_LIBRARY_PATH
/usr/local/lib:
```

My Python is:
```
$ python --version
Python 3.6.7
$ pip --version
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)
```

Thank you.

**Comment by FabriceSalvaire** [comment]
Looks like something is wrong in your installation, you must have this file (path depends of python version ... ) 

.../lib/python3.7/site-packages/CodeReview-1.0.0-py3.7-linux-x86_64.egg/EGG-INFO/scripts/pyqgit

**Comment by aiedonline** [comment]
difícil de mais, que bosta
