### ISSUE TITLE
When the current directory is not a git repo

### ISSUE THREAD

**Issue by FabriceSalvaire** [FabriceSalvaire/CodeReview#46]
```
2019-02-25 15:46:31,542 - CodeReview.GUI.LogBrowser.LogBrowserApplication - LogBrowserApplication._init_repository - INFO - Init Repository
Traceback (most recent call last):
  File "/opt/python-virtual-env/py37/bin/pyqgit", line 4, in <module>
    __import__('pkg_resources').run_script('CodeReview==1.0.0', 'pyqgit')
  File "/opt/python-virtual-env/py37/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/python-virtual-env/py37/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/home/opt/python-virtual-env/py37/lib/python3.7/site-packages/CodeReview-1.0.0-py3.7-linux-x86_64.egg/EGG-INFO/scripts/pyqgit", line 67, in <module>
    application = LogBrowserApplication(args)
  File "/opt/python-virtual-env/py37/lib64/python3.7/site-packages/CodeReview-1.0.0-py3.7-linux-x86_64.egg/CodeReview/GUI/LogBrowser/LogBrowserApplication.py", line 54, in __init__
    self.post_init()
  File "/opt/python-virtual-env/py37/lib64/python3.7/site-packages/CodeReview-1.0.0-py3.7-linux-x86_64.egg/CodeReview/GUI/LogBrowser/LogBrowserApplication.py", line 67, in post_init
    self._init_repository()
  File "/opt/python-virtual-env/py37/lib64/python3.7/site-packages/CodeReview-1.0.0-py3.7-linux-x86_64.egg/CodeReview/GUI/LogBrowser/LogBrowserApplication.py", line 97, in _init_repository
    self._repository = GitRepository(path)
  File "/opt/python-virtual-env/py37/lib64/python3.7/site-packages/CodeReview-1.0.0-py3.7-linux-x86_64.egg/CodeReview/Repository/Git.py", line 52, in __init__
    self._repository = git.Repository(repository_path)
  File "/opt/python-virtual-env/py37/lib64/python3.7/site-packages/pygit2/repository.py", line 1235, in __init__
    path = path.decode('utf-8')
AttributeError: 'NoneType' object has no attribute 'decode'
```

**Comment by FabriceSalvaire** [comment]
should be fixed
